### ISSUE TITLE
Credit card fraud detection

### ISSUE THREAD

**Issue by manideepreddym** [manideepreddym/credit-card-fraud-detection#1]
# CREDIT CARD FRAUD DETECTION
### My motivation behind this was to establish a proper system for early detection, such that organizations can identify errors, waste, and inefficiencies. This way, my contribution could increase profit and reduce losses.

[here is the link for the code and data](https://github.com/manideepreddymandhadi/credit-card-fraud-detection.git)

**Comment by manideepreddymandhadi** [comment]
For this project, I leveraged the modeling of past credit card transactions with the available data of those transactions which were exposed to be fraud.

My motivation behind this was to establish a proper system for early detection, such that organizations can identify errors, waste, and inefficiencies. This way, my contribution could increase profit and reduce losses

**Comment by manideepreddym** [comment]
[creditcard fraud detection.docx](https://github.com/manideepreddymandhadi/credit-card-fraud-detection/files/8331579/creditcard.fraud.detection.docx)

### Here is the documentation
